local GENERIC = GLOBAL.STRINGS.CHARACTERS.GENERIC

GENERIC.DESCRIBE.MERMEXP_MERM_FARMER = "SDUAHDFUIHASUIFHASJKFHJKAHWEJKFHKAWEHFKAWE"
GENERIC.DESCRIBE.MERMEXP_MERMHOUSE_FARMER = ">:)"
GENERIC.DESCRIBE.MERMEXP_MERMFARM_BLUEPRINT = "CLT (ó﹏ò｡)"
